# Generated by Django 3.2.6 on 2021-12-20 16:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content_home',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
