# Generated by Django 3.2.6 on 2021-12-21 02:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_content_home_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content_home',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
