# Generated by Django 3.2.6 on 2021-12-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_content_home_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content_home',
            name='description',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
