# Generated by Django 3.2.6 on 2021-12-22 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211222_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='content_home',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.categorie'),
            preserve_default=False,
        ),
    ]
