# Generated by Django 3.2.6 on 2021-12-27 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20211227_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='datetimee',
        ),
        migrations.AlterField(
            model_name='content_home',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.categorie'),
        ),
        migrations.DeleteModel(
            name='categorie_child',
        ),
    ]
