# Generated by Django 3.2.6 on 2021-12-27 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20211227_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='child_cate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug_child', models.SlugField(unique=True)),
                ('datetime', models.DateField(auto_now_add=True)),
                ('categorie_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.categorie')),
            ],
        ),
    ]
