# Generated by Django 3.2.6 on 2021-12-29 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_child_cate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content_home',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.child_cate'),
        ),
    ]
